# Generated by Django 5.1.15 on 2026-07-23 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('VALID', 'Valid'), ('ASSIGNED', 'Assigned'), ('INVALID', 'Invalid')], default='NEW', max_length=16)),
                ('gdpr_consent_primary', models.BooleanField()),
                ('gdpr_consent_secondary', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.passenger')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['NEW', 'VALID', 'ASSIGNED', 'INVALID'])), name='cases_case_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_category', models.CharField(choices=[('BOARDING_PASS', 'Boarding Pass'), ('IDENTIFICATION', 'Identification')], max_length=32)),
                ('original_file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size_bytes', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='case-documents/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('document_category__in', ['BOARDING_PASS', 'IDENTIFICATION'])), name='cases_uploaded_document_category_valid')],
            },
        ),
        migrations.CreateModel(
            name='FlightLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_order', models.PositiveSmallIntegerField()),
                ('flight_date', models.DateField()),
                ('flight_number', models.CharField(max_length=20)),
                ('airline', models.CharField(max_length=100)),
                ('departure_airport_code', models.CharField(max_length=10)),
                ('departure_airport_name', models.CharField(max_length=255)),
                ('destination_airport_code', models.CharField(max_length=10)),
                ('destination_airport_name', models.CharField(max_length=255)),
                ('planned_departure_time', models.DateTimeField()),
                ('planned_arrival_time', models.DateTimeField()),
                ('is_connecting_leg', models.BooleanField(default=False)),
                ('is_problem_flight', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_legs', to='cases.case')),
            ],
            options={
                'ordering': ['leg_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('leg_order__gte', 1)), name='cases_flight_leg_order_gte_1'), models.CheckConstraint(condition=models.Q(('leg_order', 1), ('is_connecting_leg', False), _connector='AND') | models.Q(('leg_order__gt', 1), ('is_connecting_leg', True), _connector='AND'), name='cases_flight_leg_connecting_flag_matches_order'), models.UniqueConstraint(fields=('case', 'leg_order'), name='cases_flight_leg_order_unique'), models.UniqueConstraint(condition=models.Q(('is_problem_flight', True)), fields=('case',), name='cases_single_problem_flight_per_case')],
            },
        ),
    ]
