# Generated by Django 5.1.15 on 2026-07-23 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_airport_code', models.CharField(max_length=10)),
                ('final_destination_code', models.CharField(max_length=10)),
                ('orthodromic_distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compensation_amount_eur', models.PositiveSmallIntegerField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='flightleg',
            name='cases_flight_leg_connecting_flag_matches_order',
        ),
        migrations.AddConstraint(
            model_name='flightleg',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_connecting_leg', False), ('leg_order', 1)), models.Q(('is_connecting_leg', True), ('leg_order__gt', 1)), _connector='OR'), name='cases_flight_leg_connecting_flag_matches_order'),
        ),
        migrations.AddField(
            model_name='compensationcalculation',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_calculation', to='cases.case'),
        ),
        migrations.AddConstraint(
            model_name='compensationcalculation',
            constraint=models.CheckConstraint(condition=models.Q(('compensation_amount_eur__in', [250, 400, 600])), name='cases_compensation_amount_valid'),
        ),
    ]
