# Generated by Django 5.1.15 on 2026-07-23 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_compensationcalculation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disruption_type', models.CharField(choices=[('CANCELLATION', 'Cancellation'), ('DELAY', 'Delay'), ('DENIED_BOARDING', 'Denied Boarding')], max_length=20)),
                ('cancellation_notice_timing', models.CharField(blank=True, default='', max_length=30)),
                ('delay_arrival_outcome', models.CharField(blank=True, default='', max_length=30)),
                ('gave_up_seat_voluntarily', models.CharField(blank=True, default='', max_length=5)),
                ('denied_boarding_reason', models.CharField(blank=True, default='', max_length=50)),
                ('airline_motive_known', models.CharField(blank=True, default='', max_length=20)),
                ('airline_motive', models.CharField(blank=True, default='', max_length=50)),
                ('incident_description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disruption', to='cases.case')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('disruption_type__in', ['CANCELLATION', 'DELAY', 'DENIED_BOARDING'])), name='cases_disruption_type_valid')],
            },
        ),
    ]
