# Generated by Django 5.1.15 on 2026-07-23 15:30

from uuid import uuid4

import apps.cases.models
from django.db import migrations, models


def generate_case_id() -> str:
    return f"CASE-{uuid4().hex[:12].upper()}"


def populate_case_ids(apps, schema_editor) -> None:
    Case = apps.get_model("cases", "Case")

    for case in Case.objects.filter(case_id__isnull=True).iterator():
        case.case_id = generate_case_id()
        case.save(update_fields=["case_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_disruption"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="assigned_colleague",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="case",
            name="case_id",
            field=models.CharField(editable=False, max_length=17, null=True),
        ),
        migrations.RunPython(populate_case_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="case",
            name="case_id",
            field=models.CharField(
                default=apps.cases.models.generate_case_id,
                editable=False,
                max_length=17,
                unique=True,
            ),
        ),
    ]