# Generated by Django 5.1.15 on 2026-07-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_passenger_user_account_and_auth_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("refreshed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["city", "name", "code"],
            },
        ),
        migrations.AddIndex(
            model_name="airport",
            index=models.Index(fields=["name"], name="cases_airport_name_idx"),
        ),
        migrations.AddIndex(
            model_name="airport",
            index=models.Index(fields=["city"], name="cases_airport_city_idx"),
        ),
    ]